import { t } from './utils.js';
import { state } from './state.js';

export const foodModals = `
    <!-- Modal for adding food to meal -->
    <div id="food-modal" class="modal">
        <div class="modal-content">
            <span class="close-btn">&times;</span>
            <h2 id="modal-title" data-t="modal_add_food_title">${t('modal_add_food_title', state.language)}</h2>
            <div id="food-search-section" class="food-selector">
                <div class="modal-tabs">
                    <button id="tab-btn-food" class="tab-btn active" data-t="tab_food">${t('tab_food', state.language)}</button>
                    <button id="tab-btn-recipes" class="tab-btn" data-t="tab_recipes">${t('tab_recipes', state.language)}</button>
                </div>
                <input type="text" id="food-search" placeholder="${t('search_placeholder', state.language)}" data-t-placeholder="search_placeholder">
                <div id="food-results" class="food-results"></div>
            </div>
            <div id="food-details-form" class="hidden">
                <p id="selected-food-display"><span data-t="selected_food">${t('selected_food', state.language)}</span> <strong id="selected-food-name"></strong></p>
                <p id="default-conv-hint" class="hidden" style="font-size: 0.7rem; color: var(--secondary); margin-bottom: 0.5rem; background: rgba(100, 181, 246, 0.1); padding: 4px 8px; border-radius: 4px; border: 1px solid rgba(100, 181, 246, 0.2);"></p>
                <div class="stats-form-grid">
                    <div class="form-group">
                        <label for="food-amount" data-t="amount_label">${t('amount_label', state.language)}</label>
                        <input type="number" id="food-amount" value="100" step="any" min="0">
                    </div>
                    <div class="form-group">
                        <label data-t="unit_label">${t('unit_label', state.language)}</label>
                        <div id="food-unit-display" style="padding: 10px; background: #252525; border: 1px solid var(--border); border-radius: 6px; color: var(--text-light); font-weight: bold;">-</div>
                        <input type="hidden" id="food-unit">
                    </div>
                </div>
                <button id="confirm-add-food" class="primary-btn" style="width:100%" data-t="confirm">${t('confirm', state.language)}</button>
            </div>
        </div>
    </div>

    <!-- Modal for pasting food text -->
    <div id="paste-modal" class="modal">
        <div class="modal-content">
            <span class="close-btn">&times;</span>
            <h2 data-t="paste_food">${t('paste_food', state.language)}</h2>
            <p style="font-size: 0.85rem; color: var(--text-light); margin-bottom: 1rem;">
                Paste text generated by an AI or from a database.
            </p>
            <textarea id="paste-area" placeholder="Paste here..." style="width: 100%; height: 200px; background: var(--input-bg); color: var(--text); border: 1px solid var(--border); border-radius: 6px; padding: 10px; margin-bottom: 1rem; font-family: monospace;"></textarea>
            <button id="confirm-paste-btn" class="primary-btn" style="width: 100%;" data-t="confirm">${t('confirm', state.language)}</button>
        </div>
    </div>
`;